pipeline {
    agent any
    
    environment {
        // Docker Hub credentials (Username/Password type in Jenkins)
        DOCKERHUB_CREDENTIALS = credentials('dockerhub-credentials')
        DOCKERHUB_USERNAME = 'abhishekc4054'

        // Image names
        BACKEND_IMAGE = "${DOCKERHUB_USERNAME}/task-manager-backend"
        FRONTEND_IMAGE = "${DOCKERHUB_USERNAME}/task-manager-frontend"

        // EC2 details
        EC2_HOST = '184.73.7.238'
        EC2_USER = 'ubuntu'

        // Build tag
        IMAGE_TAG = "${BUILD_NUMBER}"
    }
    
    stages {
        stage('Checkout Code') {
            steps {
                echo '📥 Checking out code from GitHub...'
                checkout scm
            }
        }

        stage('Build Backend Image') {
            steps {
                echo '🔨 Building Backend Docker Image...'
                dir('backend') {
                    bat """
                        docker build -t %BACKEND_IMAGE%:%IMAGE_TAG% .
                        docker tag %BACKEND_IMAGE%:%IMAGE_TAG% %BACKEND_IMAGE%:latest
                    """
                }
            }
        }

        stage('Build Frontend Image') {
            steps {
                echo '🔨 Building Frontend Docker Image...'
                dir('frontend') {
                    bat """
                        docker build -t %FRONTEND_IMAGE%:%IMAGE_TAG% .
                        docker tag %FRONTEND_IMAGE%:%IMAGE_TAG% %FRONTEND_IMAGE%:latest
                    """
                }
            }
        }

        stage('Push Images to Docker Hub') {
            steps {
                echo '📤 Pushing images to Docker Hub...'
                // Using the _USR and _PSW variables automatically generated by the credentials block
                bat """
                    echo %DOCKERHUB_CREDENTIALS_PSW% | docker login -u %DOCKERHUB_CREDENTIALS_USR% --password-stdin
                    docker push %BACKEND_IMAGE%:%IMAGE_TAG%
                    docker push %BACKEND_IMAGE%:latest
                    docker push %FRONTEND_IMAGE%:%IMAGE_TAG%
                    docker push %FRONTEND_IMAGE%:latest
                """
            }
        }

        stage('Deploy to Kubernetes (EC2)') {
            steps {
                echo '🚀 Deploying to Kubernetes on EC2 via SSH...'
                /* FIX: We use withCredentials instead of sshagent. 
                   This writes the 'ec2-ssh-key' to a temp file path stored in %KEY_FILE%
                */
                withCredentials([sshUserPrivateKey(credentialsId: 'ec2-ssh-key', keyFileVariable: 'KEY_FILE')]) {
                    bat """
                        ssh -i %KEY_FILE% -o StrictHostKeyChecking=no %EC2_USER%@%EC2_HOST% ^
                        "kubectl set image deployment/backend-deployment backend=%BACKEND_IMAGE%:%IMAGE_TAG% && ^
                         kubectl set image deployment/frontend-deployment frontend=%FRONTEND_IMAGE%:%IMAGE_TAG% && ^
                         kubectl rollout status deployment/backend-deployment && ^
                         kubectl rollout status deployment/frontend-deployment && ^
                         kubectl get pods"
                    """
                }
            }
        }
    }

    post {
        always {
            echo '🧹 Cleaning up Docker login...'
            bat 'docker logout'
        }
        success {
            echo '✅ Pipeline completed successfully!'
            echo "🌐 Access your app at: http://${EC2_HOST}:30300"
        }
        failure {
            echo '❌ Pipeline failed! Check logs above.'
        }
    }
}